// Cloudinary Configuration
// Note: Upload signatures are now generated by the backend for security
// This file is kept for any future client-side Cloudinary configurations

// Default upload options for signature requests
export const defaultUploadOptions = {
  folder: 'hadawi-dashboard',
  transformation: {
    width: 1200,
    height: 800,
    crop: 'fill',
    quality: 'auto'
  }
};
